name: Flutter CI

# Define the triggers for when the workflow should run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Run on Windows 10 environment
    runs-on: windows-latest

    strategy:
      matrix:
        flutter-version: [stable]

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter on Windows
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}

      # Run Flutter packages get to install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run unit tests
      - name: Run unit tests
        run: flutter test --coverage

